# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: All Posts, group: blog }
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categories, group: blog }

    app.repository.post:
        class: AppBundle\Repository\PostRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle:Post

    app.repository.category:
        class: AppBundle\Repository\CategoryRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle:Category